export default {
  name: 'error',
  once: false,
  async execute(bot, error) {
    // bot.log.post('error', `An error event was sent by Discord.js: \n${JSON.stringify(error)}`);
    console.log(error);

    // Report to GitHub
    bot.createGithubIssue(error, {
      additonalInfo: "Generated by Discord.js Error Handler"
    });
    
  }
};