# Main GitHub action file to deploy StenBot upon a commit

name: Docker Deployment

# on:
#   push: 
#     branches:
#       - 'master'
on: 
  workflow_dispatch

jobs: 
  redeploy: 
    name: Redeploy main instance
    runs-on: ubuntu-20.04
    steps: 
      - name: Deploy docker container webook
        uses: joelwmale/webhook-action@master
        env: 
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}