name: Post Changelog to Discord

on:
  release:
    types: [published]

jobs:
  post-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract Changelog
      id: extract_changelog
      run: |
        version=${{ github.event.release.tag_name }}
        changelog=$(awk "/## \\[${version}\\]/,/^## \\[/" CHANGELOG.md | sed '$d')
        formatted_changelog=$(echo "$changelog" | sed -e "s/## \\[${version}\\].*/**__Version ${version}__**\n/" -e "s/^### \\(.*\\)$/\n**\1**\n/g" -e "s/^- /* /" -e "s/\\*\*\\(Added\\|Changed\\|Fixed\\|Removed\\|Security\\|Deprecated\\)\\*\*/\\n\\0\\n/g")
        echo "formatted_changelog=$formatted_changelog" >> $GITHUB_ENV

    - name: Post to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        CHANGELOG_CONTENT: ${{ env.formatted_changelog }}
      run: |
        if [ -z "$CHANGELOG_CONTENT" ]; then
          echo "No changelog content found."
          exit 1
        fi
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"$CHANGELOG_CONTENT\"}" \
             $DISCORD_WEBHOOK_URL
